### ISSUE TITLE
Examples for AHI Rayleigh corrected true color

### ISSUE THREAD

**Issue by songhan89** [pytroll/pyspectral#14]
Hi,

Would it be possible to have some examples how to create Rayleigh corrected true color for AHI? Thank you very much.

**Comment by adybbroe** [comment]
Hi,
I have just added a jupyter notebook example here:
https://github.com/pytroll/pytroll-examples/blob/master/satpy/ahi_true_color_pyspectral.ipynb

**Comment by songhan89** [comment]
Thank you very much for the quick response!

**Comment by adioses** [comment]
Hi, 
Would it be possible to have the same example for GOES-16. 
I'm trying to use NetCDF files to generate Rayleigh corrected true color, I also would like to know the equations to calculate solar-zenith angle, satellite zenith angle, and the relative sun-satellite azimuth difference angle in order to understand better this corrections. Thank you very much

**Comment by djhoese** [comment]
@adioses This is a rather old issue. Would you mind opening up a new issue for your specific request? Could you also include what about the AHI example isn't clear that you can't apply it to ABI (reader name is `abi_l1b`)? @adybbroe could probably link you to the paper where they discuss their Rayleigh correction. I don't have it available right now but that may answer some of your questions.

**Comment by adioses** [comment]
I'm very new on GitHub and Pytroll. I'll try what you just suggest. If you could share the paper would be great. Thanks
